package bean;
// Generated 10/10/2025 15:05:30 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JmjBebidas generated by hbm2java
 */
@Entity
@Table(name = "JMJ_Bebidas",
         catalog = "db_julia_rogoski"
)

public class JmjBebidas implements java.io.Serializable {

    private int jmjIdBebidas;
    private String jmjNome;
    private int jmjTipo;
    private double jmjPreco;
    private String jmjFabricante;
    private String jmjTeorAlcoolico;
    private String jmjVolumeMl;
    private String jmjAtivo;

    public JmjBebidas() {
        // Construtor sem parâmetros (opcional)
    }

    public JmjBebidas(int jmjIdBebidas, String jmjNome, int jmjTipo, double jmjPreco, String jmjFabricante, String jmjTeorAlcoolico, String jmjVolumeMl, String jmjAtivo) {
        this.jmjIdBebidas = jmjIdBebidas;
        this.jmjNome = jmjNome;
        this.jmjTipo = jmjTipo;
        this.jmjPreco = jmjPreco;
        this.jmjFabricante = jmjFabricante;
        this.jmjTeorAlcoolico = jmjTeorAlcoolico;
        this.jmjVolumeMl = jmjVolumeMl;
        this.jmjAtivo = jmjAtivo;
    }

    @Id

    @Column(name = "jmj_idBebidas", unique = true, nullable = false)
    public int getJmjIdBebidas() {
        return this.jmjIdBebidas;
    }

    public void setJmjIdBebidas(int jmjIdBebidas) {
        this.jmjIdBebidas = jmjIdBebidas;
    }

    @Column(name = "jmj_nome", nullable = false, length = 100)
    public String getJmjNome() {
        return this.jmjNome;
    }

    public void setJmjNome(String jmjNome) {
        this.jmjNome = jmjNome;
    }

    @Column(name = "jmj_tipo", nullable = false)
    public int getJmjTipo() {
        return this.jmjTipo;
    }

    public void setJmjTipo(int jmjTipo) {
        this.jmjTipo = jmjTipo;
    }

    @Column(name = "jmj_preco", nullable = false, length = 10)
    public double getJmjPreco() {
        return this.jmjPreco;
    }

    public void setJmjPreco(double jmjPreco) {
        this.jmjPreco = jmjPreco;
    }

    @Column(name = "jmj_fabricante", nullable = false, length = 100)
    public String getJmjFabricante() {
        return this.jmjFabricante;
    }

    public void setJmjFabricante(String jmjFabricante) {
        this.jmjFabricante = jmjFabricante;
    }

    @Column(name = "jmj_teorAlcoolico", nullable = false, length = 10)
    public String getJmjTeorAlcoolico() {
        return this.jmjTeorAlcoolico;
    }

    public void setJmjTeorAlcoolico(String jmjTeorAlcoolico) {
        this.jmjTeorAlcoolico = jmjTeorAlcoolico;
    }

    @Column(name = "jmj_volume_ml", nullable = false, length = 10)
    public String getJmjVolumeMl() {
        return this.jmjVolumeMl;
    }

    public void setJmjVolumeMl(String jmjVolumeMl) {
        this.jmjVolumeMl = jmjVolumeMl;
    }

    @Column(name = "jmj_ativo", nullable = false, length = 1)
    public String getJmjAtivo() {
        return this.jmjAtivo;
    }

    public void setJmjAtivo(String jmjAtivo) {
        this.jmjAtivo = jmjAtivo;
    }

    public boolean equals(Object object) {
        if (object instanceof JmjBebidas) {
            JmjBebidas produtos = (JmjBebidas) object;
            if (this.getJmjIdBebidas() == produtos.getJmjIdBebidas()) {
                return true;
            }
        }
        return false;
    }

}
