package bean;
// Generated 10/10/2025 15:05:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmjClientes generated by hbm2java
 */
@Entity
@Table(name="JMJ_Clientes"
    ,catalog="db_julia_rogoski"
)
public class JmjClientes  implements java.io.Serializable {


     private int jmjIdClientes;
     private String jmjNome;
     private String jmjCpf;
     private String jmjRg;
     private int jmjSexo;
     private Date jmjDataNascimento;
     private String jmjEmail;
     private String jmjTelefone;
     private String jmjCelular;
     private String jmjCep;
     private String jmjCnpj;
     private String jmjBairro;
     private String jmjEndereco;
     private String jmjCidade;
     private String jmjUf;
     private Date jmjDataCadastro;
     private String jmjAtivo;

    public JmjClientes() {
    }

	
    public JmjClientes(int jmjIdClientes, String jmjNome, String jmjCpf, String jmjRg, int jmjSexo, Date jmjDataNascimento, String jmjEmail, String jmjTelefone, String jmjCelular, String jmjCep, String Cnpj, String jmjBairro, String jmjEndereco, String jmjCidade, String jmjUf, Date jmjDataCadastro, String jmjAtivo) {
        this.jmjIdClientes = jmjIdClientes;
        this.jmjNome = jmjNome;
        this.jmjCpf = jmjCpf;
        this.jmjRg = jmjRg;
        this.jmjSexo = jmjSexo;
        this.jmjDataNascimento = jmjDataNascimento;
        this.jmjEmail = jmjEmail;
        this.jmjTelefone = jmjTelefone;
        this.jmjCelular = jmjCelular;
        this.jmjCep = jmjCep;
        this.jmjCnpj = jmjCnpj;
        this.jmjBairro = jmjBairro;
        this.jmjEndereco = jmjEndereco;
        this.jmjCidade = jmjCidade;
        this.jmjUf = jmjUf;
        this.jmjDataCadastro = jmjDataCadastro;
        this.jmjAtivo = jmjAtivo;
    }
    public JmjClientes(int jmjIdClientes, String jmjNome, String jmjCpf, String jmjRg, int jmjSexo, Date jmjDataNascimento, String jmjEmail, String jmjTelefone, String jmjCelular, String jmjCep, String jmjCnpj, String jmjBairro, String jmjEndereco, String jmjCidade, String jmjUf, Date jmjDataCadastro, String jmjAtivo, Set jmjVendases) {
       this.jmjIdClientes = jmjIdClientes;
       this.jmjNome = jmjNome;
       this.jmjCpf = jmjCpf;
       this.jmjRg = jmjRg;
       this.jmjSexo = jmjSexo;
       this.jmjDataNascimento = jmjDataNascimento;
       this.jmjEmail = jmjEmail;
       this.jmjTelefone = jmjTelefone;
       this.jmjCelular = jmjCelular;
       this.jmjCep = jmjCep;
       this.jmjCnpj = jmjCnpj;
       this.jmjBairro = jmjBairro;
       this.jmjEndereco = jmjEndereco;
       this.jmjCidade = jmjCidade;
       this.jmjUf = jmjUf;
       this.jmjDataCadastro = jmjDataCadastro;
       this.jmjAtivo = jmjAtivo;
    }
   
     @Id 

    
    @Column(name="jmj_idClientes", unique=true, nullable=false)
    public int getJmjIdClientes() {
        return this.jmjIdClientes;
    }
    
    public void setJmjIdClientes(int jmjIdClientes) {
        this.jmjIdClientes = jmjIdClientes;
    }

    
    @Column(name="jmj_nome", nullable=false, length=100)
    public String getJmjNome() {
        return this.jmjNome;
    }
    
    public void setJmjNome(String jmjNome) {
        this.jmjNome = jmjNome;
    }

    
    @Column(name="jmj_cpf", nullable=false, length=14)
    public String getJmjCpf() {
        return this.jmjCpf;
    }
    
    public void setJmjCpf(String jmjCpf) {
        this.jmjCpf = jmjCpf;
    }

    
    @Column(name="jmj_rg", nullable=false, length=45)
    public String getJmjRg() {
        return this.jmjRg;
    }
    
    public void setJmjRg(String jmjRg) {
        this.jmjRg = jmjRg;
    }

    
    @Column(name="jmj_sexo", nullable=false)
    public int getJmjSexo() {
        return this.jmjSexo;
    }
    
    public void setJmjSexo(int jmjSexo) {
        this.jmjSexo = jmjSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmj_dataNascimento", nullable=false, length=10)
    public Date getJmjDataNascimento() {
        return this.jmjDataNascimento;
    }
    
    public void setJmjDataNascimento(Date jmjDataNascimento) {
        this.jmjDataNascimento = jmjDataNascimento;
    }

    
    @Column(name="jmj_email", nullable=false, length=80)
    public String getJmjEmail() {
        return this.jmjEmail;
    }
    
    public void setJmjEmail(String jmjEmail) {
        this.jmjEmail = jmjEmail;
    }

    
    @Column(name="jmj_telefone", nullable=false, length=10)
    public String getJmjTelefone() {
        return this.jmjTelefone;
    }
    
    public void setJmjTelefone(String jmjTelefone) {
        this.jmjTelefone = jmjTelefone;
    }

    
    @Column(name="jmj_celular", nullable=false, length=14)
    public String getJmjCelular() {
        return this.jmjCelular;
    }
    
    public void setJmjCelular(String jmjCelular) {
        this.jmjCelular = jmjCelular;
    }

    
    @Column(name="jmj_cep", nullable=false, length=9)
    public String getJmjCep() {
        return this.jmjCep;
    }
    
    public void setJmjCep(String jmjCep) {
        this.jmjCep = jmjCep;
    }
    
    @Column(name="jmj_cnpj", nullable=false, length=18)
    public String getJmjCnpj() {
        return this.jmjCnpj;
    }
    
    public void setJmjCnpj(String jmjCnpj) {
        this.jmjCnpj = jmjCnpj;
    }

    
    @Column(name="jmj_bairro", nullable=false, length=30)
    public String getJmjBairro() {
        return this.jmjBairro;
    }
    
    public void setJmjBairro(String jmjBairro) {
        this.jmjBairro = jmjBairro;
    }

    
    @Column(name="jmj_endereco", nullable=false, length=50)
    public String getJmjEndereco() {
        return this.jmjEndereco;
    }
    
    public void setJmjEndereco(String jmjEndereco) {
        this.jmjEndereco = jmjEndereco;
    }

    
    @Column(name="jmj_cidade", nullable=false, length=50)
    public String getJmjCidade() {
        return this.jmjCidade;
    }
    
    public void setJmjCidade(String jmjCidade) {
        this.jmjCidade = jmjCidade;
    }

    
    @Column(name="jmj_uf", nullable=false, length=2)
    public String getJmjUf() {
        return this.jmjUf;
    }
    
    public void setJmjUf(String jmjUf) {
        this.jmjUf = jmjUf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmj_dataCadastro", nullable=false, length=10)
    public Date getJmjDataCadastro() {
        return this.jmjDataCadastro;
    }
    
    public void setJmjDataCadastro(Date jmjDataCadastro) {
        this.jmjDataCadastro = jmjDataCadastro;
    }

    
    @Column(name="jmj_ativo", nullable=false, length=1)
    public String getJmjAtivo() {
        return this.jmjAtivo;
    }
    
    public void setJmjAtivo(String jmjAtivo) {
        this.jmjAtivo = jmjAtivo;
    }



}


