package bean;
// Generated 07/10/2025 14:08:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmjUsuarios generated by hbm2java
 */
@Entity
@Table(name="JMJ_Usuarios"
    ,catalog="db_julia_rogoski"
)
public class JmjUsuarios  implements java.io.Serializable {


     private int jmjIdUsuarios;
     private String jmjNome;
     private String jmjApelido;
     private String jmjCpf;
     private Date jmjDataNascimento;
     private String jmjSenha;
     private int jmjNivel;
     private String jmjAtivo;

    public JmjUsuarios() {
    }

    public JmjUsuarios(int jmjIdUsuarios, String jmjNome, String jmjApelido, String jmjCpf, Date jmjDataNascimento, String jmjSenha, int jmjNivel, String jmjAtivo) {
       this.jmjIdUsuarios = jmjIdUsuarios;
       this.jmjNome = jmjNome;
       this.jmjApelido = jmjApelido;
       this.jmjCpf = jmjCpf;
       this.jmjDataNascimento = jmjDataNascimento;
       this.jmjSenha = jmjSenha;
       this.jmjNivel = jmjNivel;
       this.jmjAtivo = jmjAtivo;
    }
   
     @Id 

    
    @Column(name="jmj_idUsuarios", unique=true, nullable=false)
    public int getJmjIdUsuarios() {
        return this.jmjIdUsuarios;
    }
    
    public void setJmjIdUsuarios(int jmjIdUsuarios) {
        this.jmjIdUsuarios = jmjIdUsuarios;
    }

    
    @Column(name="jmj_nome", nullable=false, length=100)
    public String getJmjNome() {
        return this.jmjNome;
    }
    
    public void setJmjNome(String jmjNome) {
        this.jmjNome = jmjNome;
    }

    
    @Column(name="jmj_apelido", nullable=false, length=45)
    public String getJmjApelido() {
        return this.jmjApelido;
    }
    
    public void setJmjApelido(String jmjApelido) {
        this.jmjApelido = jmjApelido;
    }

    
    @Column(name="jmj_cpf", nullable=false, length=11)
    public String getJmjCpf() {
        return this.jmjCpf;
    }
    
    public void setJmjCpf(String jmjCpf) {
        this.jmjCpf = jmjCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmj_dataNascimento", nullable=false, length=10)
    public Date getJmjDataNascimento() {
        return this.jmjDataNascimento;
    }
    
    public void setJmjDataNascimento(Date jmjDataNascimento) {
        this.jmjDataNascimento = jmjDataNascimento;
    }

    
    @Column(name="jmj_senha", nullable=false, length=20)
    public String getJmjSenha() {
        return this.jmjSenha;
    }
    
    public void setJmjSenha(String jmjSenha) {
        this.jmjSenha = jmjSenha;
    }

    
    @Column(name="jmj_nivel", nullable=false)
    public int getJmjNivel() {
        return this.jmjNivel;
    }
    
    public void setJmjNivel(int jmjNivel) {
        this.jmjNivel = jmjNivel;
    }

    
    @Column(name="jmj_ativo", nullable=false, length=1)
    public String getJmjAtivo() {
        return this.jmjAtivo;
    }
    
    public void setJmjAtivo(String jmjAtivo) {
        this.jmjAtivo = jmjAtivo;
    }




}


