package bean;
// Generated 07/10/2025 14:08:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JmjVendasBebidas generated by hbm2java
 */
@Entity
@Table(name="JMJ_Vendas_Bebidas"
    ,catalog="db_julia_rogoski"
)
public class JmjVendasBebidas  implements java.io.Serializable {


     private Integer jmjIdVendasBebidas;
     private Integer jmjIdVendas;
     private Integer jmjIdBebidas;
     private Integer jmjQuantidade;
     private double jmjPrecoUnitario;
     private double jmjSubtotal;
     private double jmjDesconto;

    public JmjVendasBebidas() {
    }

    public JmjVendasBebidas(Integer jmjIdVendas, Integer jmjIdBebidas, Integer jmjQuantidade, double jmjPrecoUnitario, double jmjSubtotal, double jmjDesconto) {
       this.jmjIdVendas = jmjIdVendas;
       this.jmjIdBebidas = jmjIdBebidas;
       this.jmjQuantidade = jmjQuantidade;
       this.jmjPrecoUnitario = jmjPrecoUnitario;
       this.jmjSubtotal = jmjSubtotal;
       this.jmjDesconto = jmjDesconto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jmj_idVendas_Bebidas", unique=true, nullable=false)
    public Integer getJmjIdVendasBebidas() {
        return this.jmjIdVendasBebidas;
    }
    
    public void setJmjIdVendasBebidas(Integer jmjIdVendasBebidas) {
        this.jmjIdVendasBebidas = jmjIdVendasBebidas;
    }

    
    @Column(name="jmj_idVendas")
    public Integer getJmjIdVendas() {
        return this.jmjIdVendas;
    }
    
    public void setJmjIdVendas(Integer jmjIdVendas) {
        this.jmjIdVendas = jmjIdVendas;
    }

    
    @Column(name="jmj_idBebidas")
    public Integer getJmjIdBebidas() {
        return this.jmjIdBebidas;
    }
    
    public void setJmjIdBebidas(Integer jmjIdBebidas) {
        this.jmjIdBebidas = jmjIdBebidas;
    }

    
    @Column(name="jmj_quantidade")
    public Integer getJmjQuantidade() {
        return this.jmjQuantidade;
    }
    
    public void setJmjQuantidade(Integer jmjQuantidade) {
        this.jmjQuantidade = jmjQuantidade;
    }

    
    @Column(name="jmj_preco_unitario", precision=10)
    public double getJmjPrecoUnitario() {
        return this.jmjPrecoUnitario;
    }
    
    public void setJmjPrecoUnitario(double jmjPrecoUnitario) {
        this.jmjPrecoUnitario = jmjPrecoUnitario;
    }

    
    @Column(name="jmj_subtotal", precision=10)
    public double getJmjSubtotal() {
        return this.jmjSubtotal;
    }
    
    public void setJmjSubtotal(double jmjSubtotal) {
        this.jmjSubtotal = jmjSubtotal;
    }

    
    @Column(name="jmj_desconto", precision=10)
    public double getJmjDesconto() {
        return this.jmjDesconto;
    }
    
    public void setJmjDesconto(double jmjDesconto) {
        this.jmjDesconto = jmjDesconto;
    }




}


