package bean;
// Generated 07/10/2025 14:08:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmjVendas generated by hbm2java
 */
@Entity
@Table(name="JMJ_Vendas"
    ,catalog="db_julia_rogoski"
)
public class JmjVendas  implements java.io.Serializable {


     private int jmjIdVendas;
     private int jmjIdClientes;
     private Date jmjDataVenda;
     private String jmjSituacao;
     private double jmjTotal;
     private String jmjFormaPagamento;
     private String jmjObservacao;

    public JmjVendas() {
    }

    public JmjVendas(int jmjIdClientes, Date jmjDataVenda, String jmjSituacao, double jmjTotal, String jmjFormaPagamento, String jmjObservacao) {
       this.jmjIdClientes = jmjIdClientes;
       this.jmjDataVenda = jmjDataVenda;
       this.jmjSituacao = jmjSituacao;
       this.jmjTotal = jmjTotal;
       this.jmjFormaPagamento = jmjFormaPagamento;
       this.jmjObservacao = jmjObservacao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jmj_idVendas", unique=true, nullable=false)
    public int getJmjIdVendas() {
        return this.jmjIdVendas;
    }
    
    public void setJmjIdVendas(int jmjIdVendas) {
        this.jmjIdVendas = jmjIdVendas;
    }

    
    @Column(name="jmj_idClientes")
    public int getJmjIdClientes() {
        return this.jmjIdClientes;
    }
    
    public void setJmjIdClientes(int jmjIdClientes) {
        this.jmjIdClientes = jmjIdClientes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmj_data_venda", length=10)
    public Date getJmjDataVenda() {
        return this.jmjDataVenda;
    }
    
    public void setJmjDataVenda(Date jmjDataVenda) {
        this.jmjDataVenda = jmjDataVenda;
    }

    
    @Column(name="jmj_situacao", length=20)
    public String getJmjSituacao() {
        return this.jmjSituacao;
    }
    
    public void setJmjSituacao(String jmjSituacao) {
        this.jmjSituacao = jmjSituacao;
    }

    
    @Column(name="jmj_total", precision=10)
    public double getJmjTotal() {
        return this.jmjTotal;
    }
    
    public void setJmjTotal(double jmjTotal) {
        this.jmjTotal = jmjTotal;
    }

    
    @Column(name="jmj_forma_pagamento", length=50)
    public String getJmjFormaPagamento() {
        return this.jmjFormaPagamento;
    }
    
    public void setJmjFormaPagamento(String jmjFormaPagamento) {
        this.jmjFormaPagamento = jmjFormaPagamento;
    }

    
    @Column(name="jmj_observacao", length=100)
    public String getJmjObservacao() {
        return this.jmjObservacao;
    }
    
    public void setJmjObservacao(String jmjObservacao) {
        this.jmjObservacao = jmjObservacao;
    }




}


