package bean;
// Generated 10/10/2025 15:05:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JmjVendedor generated by hbm2java
 */
@Entity
@Table(name="JMJ_Vendedor"
    ,catalog="db_julia_rogoski"
)
public class JmjVendedor  implements java.io.Serializable {


     private int jmjIdVendedor;
     private String jmjNome;
     private String jmjCpf;
     private String jmjEmail;
     private String jmjTelefone;
     private String jmjCelular;
     private String jmjAtivo;
     private String jmjApelido;

    public JmjVendedor() {
    }

	
    public JmjVendedor(int jmjIdVendedor, String jmjNome, String jmjCpf, String jmjEmail, String jmjTelefone, String jmjCelular, String jmjAtivo, String jmjApelido) {
        this.jmjIdVendedor = jmjIdVendedor;
        this.jmjNome = jmjNome;
        this.jmjCpf = jmjCpf;
        this.jmjEmail = jmjEmail;
        this.jmjTelefone = jmjTelefone;
        this.jmjCelular = jmjCelular;
        this.jmjAtivo = jmjAtivo;
        this.jmjApelido = jmjApelido;
    }
    public JmjVendedor(int jmjIdVendedor, String jmjNome, String jmjCpf, String jmjEmail, String jmjTelefone, String jmjCelular, String jmjAtivo, String jmjApelido, Set jmjVendases) {
       this.jmjIdVendedor = jmjIdVendedor;
       this.jmjNome = jmjNome;
       this.jmjCpf = jmjCpf;
       this.jmjEmail = jmjEmail;
       this.jmjTelefone = jmjTelefone;
       this.jmjCelular = jmjCelular;
       this.jmjAtivo = jmjAtivo;
       this.jmjApelido = jmjApelido;
    }
   
     @Id 

    
    @Column(name="jmj_idVendedor", unique=true, nullable=false)
    public int getJmjIdVendedor() {
        return this.jmjIdVendedor;
    }
    
    public void setJmjIdVendedor(int jmjIdVendedor) {
        this.jmjIdVendedor = jmjIdVendedor;
    }

    
    @Column(name="jmj_nome", nullable=false, length=50)
    public String getJmjNome() {
        return this.jmjNome;
    }
    
    @Column(name="jmj_apelido", nullable=false, length=45)
    public String getJmjApelido() {
        return this.jmjApelido;
    }
    
    public void setJmjApelido(String jmjApelido) {
        this.jmjApelido = jmjApelido;
    }
    
    public void setJmjNome(String jmjNome) {
        this.jmjNome = jmjNome;
    }

    
    @Column(name="jmj_cpf", nullable=false, length=14)
    public String getJmjCpf() {
        return this.jmjCpf;
    }
    
    public void setJmjCpf(String jmjCpf) {
        this.jmjCpf = jmjCpf;
    }

    
    @Column(name="jmj_email", nullable=false, length=80)
    public String getJmjEmail() {
        return this.jmjEmail;
    }
    
    public void setJmjEmail(String jmjEmail) {
        this.jmjEmail = jmjEmail;
    }

    
    @Column(name="jmj_telefone", nullable=false, length=10)
    public String getJmjTelefone() {
        return this.jmjTelefone;
    }
    
    public void setJmjTelefone(String jmjTelefone) {
        this.jmjTelefone = jmjTelefone;
    }

    
    @Column(name="jmj_celular", nullable=false, length=14)
    public String getJmjCelular() {
        return this.jmjCelular;
    }
    
    public void setJmjCelular(String jmjCelular) {
        this.jmjCelular = jmjCelular;
    }

    
    @Column(name="jmj_ativo", nullable=false, length=1)
    public String getJmjAtivo() {
        return this.jmjAtivo;
    }
    
    public void setJmjAtivo(String jmjAtivo) {
        this.jmjAtivo = jmjAtivo;
    }

    
    


}


