package bean;
// Generated 07/10/2025 14:08:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmjVendedor generated by hbm2java
 */
@Entity
@Table(name="JMJ_Vendedor"
    ,catalog="db_julia_rogoski"
)
public class JmjVendedor  implements java.io.Serializable {


     private int jmjIdVendedor;
     private String jmjNome;
     private String jmjCpf;
     private String jmjEmail;
     private Date jmjDataNascimento;
     private String jmjTelefone;
     private String jmjCelular;
     private String jmjCep;
     private String jmjEndereco;
     private String jmjBairro;
     private String jmjCidade;
     private String jmjUf;
     private Date jmjDataEmissao;
     private String jmjAtivo;

    public JmjVendedor() {
    }

    public JmjVendedor(int jmjIdVendedor, String jmjNome, String jmjCpf, String jmjEmail, Date jmjDataNascimento, String jmjTelefone, String jmjCelular, String jmjCep, String jmjEndereco, String jmjBairro, String jmjCidade, String jmjUf, Date jmjDataEmissao, String jmjAtivo) {
       this.jmjIdVendedor = jmjIdVendedor;
       this.jmjNome = jmjNome;
       this.jmjCpf = jmjCpf;
       this.jmjEmail = jmjEmail;
       this.jmjDataNascimento = jmjDataNascimento;
       this.jmjTelefone = jmjTelefone;
       this.jmjCelular = jmjCelular;
       this.jmjCep = jmjCep;
       this.jmjEndereco = jmjEndereco;
       this.jmjBairro = jmjBairro;
       this.jmjCidade = jmjCidade;
       this.jmjUf = jmjUf;
       this.jmjDataEmissao = jmjDataEmissao;
       this.jmjAtivo = jmjAtivo;
    }
   
     @Id 

    
    @Column(name="jmj_idVendedor", unique=true, nullable=false)
    public int getJmjIdVendedor() {
        return this.jmjIdVendedor;
    }
    
    public void setJmjIdVendedor(int jmjIdVendedor) {
        this.jmjIdVendedor = jmjIdVendedor;
    }

    
    @Column(name="jmj_nome", nullable=false, length=50)
    public String getJmjNome() {
        return this.jmjNome;
    }
    
    public void setJmjNome(String jmjNome) {
        this.jmjNome = jmjNome;
    }

    
    @Column(name="jmj_cpf", nullable=false, length=14)
    public String getJmjCpf() {
        return this.jmjCpf;
    }
    
    public void setJmjCpf(String jmjCpf) {
        this.jmjCpf = jmjCpf;
    }

    
    @Column(name="jmj_email", nullable=false, length=80)
    public String getJmjEmail() {
        return this.jmjEmail;
    }
    
    public void setJmjEmail(String jmjEmail) {
        this.jmjEmail = jmjEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmj_dataNascimento", nullable=false, length=10)
    public Date getJmjDataNascimento() {
        return this.jmjDataNascimento;
    }
    
    public void setJmjDataNascimento(Date jmjDataNascimento) {
        this.jmjDataNascimento = jmjDataNascimento;
    }

    
    @Column(name="jmj_telefone", nullable=false, length=10)
    public String getJmjTelefone() {
        return this.jmjTelefone;
    }
    
    public void setJmjTelefone(String jmjTelefone) {
        this.jmjTelefone = jmjTelefone;
    }

    
    @Column(name="jmj_celular", nullable=false, length=14)
    public String getJmjCelular() {
        return this.jmjCelular;
    }
    
    public void setJmjCelular(String jmjCelular) {
        this.jmjCelular = jmjCelular;
    }

    
    @Column(name="jmj_cep", nullable=false, length=9)
    public String getJmjCep() {
        return this.jmjCep;
    }
    
    public void setJmjCep(String jmjCep) {
        this.jmjCep = jmjCep;
    }

    
    @Column(name="jmj_endereco", nullable=false, length=50)
    public String getJmjEndereco() {
        return this.jmjEndereco;
    }
    
    public void setJmjEndereco(String jmjEndereco) {
        this.jmjEndereco = jmjEndereco;
    }

    
    @Column(name="jmj_bairro", nullable=false, length=30)
    public String getJmjBairro() {
        return this.jmjBairro;
    }
    
    public void setJmjBairro(String jmjBairro) {
        this.jmjBairro = jmjBairro;
    }

    
    @Column(name="jmj_cidade", nullable=false, length=50)
    public String getJmjCidade() {
        return this.jmjCidade;
    }
    
    public void setJmjCidade(String jmjCidade) {
        this.jmjCidade = jmjCidade;
    }

    
    @Column(name="jmj_uf", nullable=false, length=2)
    public String getJmjUf() {
        return this.jmjUf;
    }
    
    public void setJmjUf(String jmjUf) {
        this.jmjUf = jmjUf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmj_dataEmissao", nullable=false, length=10)
    public Date getJmjDataEmissao() {
        return this.jmjDataEmissao;
    }
    
    public void setJmjDataEmissao(Date jmjDataEmissao) {
        this.jmjDataEmissao = jmjDataEmissao;
    }

    
    @Column(name="jmj_ativo", nullable=false, length=1)
    public String getJmjAtivo() {
        return this.jmjAtivo;
    }
    
    public void setJmjAtivo(String jmjAtivo) {
        this.jmjAtivo = jmjAtivo;
    }




}


