package bean;
// Generated 10/10/2025 14:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JmjVendas generated by hbm2java
 */
@Entity
@Table(name="JMJ_Vendas"
    ,catalog="db_julia_rogoski"
)
public class JmjVendas  implements java.io.Serializable {


     private Integer jmjIdVendas;
     private JmjClientes jmjClientesByJmjFkVendedor;
     private JmjClientes jmjClientesByJmjFkClientes;
     private String jmjDataVenda;
     private String jmjTotalVenda;

    public JmjVendas() {
    }

	
    public JmjVendas(JmjClientes jmjClientesByJmjFkVendedor, String jmjDataVenda, String jmjTotalVenda) {
        this.jmjClientesByJmjFkVendedor = jmjClientesByJmjFkVendedor;
        this.jmjDataVenda = jmjDataVenda;
        this.jmjTotalVenda = jmjTotalVenda;
    }
    public JmjVendas(JmjClientes jmjClientesByJmjFkVendedor, JmjClientes jmjClientesByJmjFkClientes, String jmjDataVenda, String jmjTotalVenda, Set jmjVendasBebidases) {
       this.jmjClientesByJmjFkVendedor = jmjClientesByJmjFkVendedor;
       this.jmjClientesByJmjFkClientes = jmjClientesByJmjFkClientes;
       this.jmjDataVenda = jmjDataVenda;
       this.jmjTotalVenda = jmjTotalVenda;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jmj_idVendas", unique=true, nullable=false)
    public Integer getJmjIdVendas() {
        return this.jmjIdVendas;
    }
    
    public void setJmjIdVendas(Integer jmjIdVendas) {
        this.jmjIdVendas = jmjIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmj_fkVendedor", nullable=false)
    public JmjClientes getJmjClientesByJmjFkVendedor() {
        return this.jmjClientesByJmjFkVendedor;
    }
    
    public void setJmjClientesByJmjFkVendedor(JmjClientes jmjClientesByJmjFkVendedor) {
        this.jmjClientesByJmjFkVendedor = jmjClientesByJmjFkVendedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmj_fkClientes")
    public JmjClientes getJmjClientesByJmjFkClientes() {
        return this.jmjClientesByJmjFkClientes;
    }
    
    public void setJmjClientesByJmjFkClientes(JmjClientes jmjClientesByJmjFkClientes) {
        this.jmjClientesByJmjFkClientes = jmjClientesByJmjFkClientes;
    }

    
    @Column(name="jmj_dataVenda", nullable=false, length=20)
    public String getJmjDataVenda() {
        return this.jmjDataVenda;
    }
    
    public void setJmjDataVenda(String jmjDataVenda) {
        this.jmjDataVenda = jmjDataVenda;
    }

    
    @Column(name="jmj_totalVenda", nullable=false, length=50)
    public String getJmjTotalVenda() {
        return this.jmjTotalVenda;
    }
    
    public void setJmjTotalVenda(String jmjTotalVenda) {
        this.jmjTotalVenda = jmjTotalVenda;
    }


}


