package bean;
// Generated 10/10/2025 15:05:30 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JmjVendasBebidas generated by hbm2java
 */
@Entity
@Table(name="JMJ_Vendas_Bebidas"
    ,catalog="db_julia_rogoski"
)
public class JmjVendasBebidas  implements java.io.Serializable {


     private Integer jmjIdVendasBebidas;
     private JmjBebidas jmjBebidas;
     private JmjVendas jmjVendas;
     private int jmjQuantidade;
     private double jmjTotalBebidas;
     private double jmjPreco;

    public JmjVendasBebidas() {
    }

    public JmjVendasBebidas(JmjBebidas jmjBebidas, JmjVendas jmjVendas, int jmjQuantidade, double jmjTotalBebidas, double jmjDesconto) {
       this.jmjBebidas = jmjBebidas;
       this.jmjVendas = jmjVendas;
       this.jmjQuantidade = jmjQuantidade;
       this.jmjTotalBebidas = jmjTotalBebidas;
       this.jmjPreco = jmjPreco;
    }
   
     @Id 

    @Column(name="jmj_idVendas_Bebidas", unique=true, nullable=false)
    public Integer getJmjIdVendasBebidas() {
        return this.jmjIdVendasBebidas;
    }
    
    public void setJmjIdVendasBebidas(Integer jmjIdVendasBebidas) {
        this.jmjIdVendasBebidas = jmjIdVendasBebidas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmj_fkBebidas", nullable=false)
    public JmjBebidas getJmjBebidas() {
        return this.jmjBebidas;
    }
    
    public void setJmjBebidas(JmjBebidas jmjBebidas) {
        this.jmjBebidas = jmjBebidas;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmj_fkVendas", nullable=false)
    public JmjVendas getJmjVendas() {
        return this.jmjVendas;
    }
    
    public void setJmjVendas(JmjVendas jmjVendas) {
        this.jmjVendas = jmjVendas;
    }

    
    @Column(name="jmj_quantidade", nullable=false)
    public int getJmjQuantidade() {
        return this.jmjQuantidade;
    }
    
    public void setJmjQuantidade(int jmjQuantidade) {
        this.jmjQuantidade = jmjQuantidade;
    }

    
    @Column(name="jmj_TotalBebidas", nullable=false, precision=10)
    public double getJmjTotalBebidas() {
        return this.jmjTotalBebidas;
    }
    
    public void setJmjTotalBebidas(double jmjTotalBebidas) {
        this.jmjTotalBebidas = jmjTotalBebidas;
    }

    
    @Column(name="jmj_preco", nullable=false, precision=10)
    public double getJmjPreco() {
        return this.jmjPreco;
    }
    
    public void setJmjPreco(double jmjPreco) {
        this.jmjPreco = jmjPreco;
    }

}


